### ISSUE TITLE
Developer Quiz: Duplicate multiple choice option in a question from the Python section

### ISSUE THREAD

**Issue by j-dover** [freeCodeCamp/LearnToCodeRPG#15]
### What bug did you encounter?

Operating System: Windows 10

When I took the Python section of the Developer Quiz, I encountered a bug in this question: _Which one of the following options prints "Hello, World!" without starting a new line at the end?_

Two multiple choice options appear as `print("Hello, World!", end="")`. I chose the first occurrence which was the correct answer.

When I reproduced this bug the first time, I chose the second `print("Hello, World!", end="")`. This choice resulted in a "Wrong..." answer and then displayed the correct answer after continuing with the game. However, the displayed correct answer appeared the same as the second `print("Hello, World!", end="")`.

 I tried reproducing the bug again with the first `print("Hello, World!", end="")` option. This choice resulted in a "Correct!" response.

### Steps to Reproduce

1. By using the Save menu, I saved the game in a save slot before picking an answer above. I clicked the first `print("Hello, World!", end="")` option and received a correct response.
2. Then, I went to the Settings menu to use the Load Game menu.
3. In the Load Game menu, I chose to load the saved game slot from Step 1.
4. I repeated steps 2-4 until I encountered the question _Which one of the following options prints "Hello, World!" without starting a new line at the end?_ again. This was necessary because the quiz questions appear randomly.
5. To get a "Correct!" response, I chose the first `print("Hello, World!", end="")`. To get a "Wrong..." response, I picked the second `print("Hello, World!", end="")`.

### Screenshots

First occurrence of the bug:
![learnToCodeRPG_python_quiz_ui_bug](https://user-images.githubusercontent.com/15676972/147284426-64b1562b-6af3-4f0a-9b7a-0ab06e770a38.jpg)

Reproducing the bug and choosing the second `print("Hello, World!", end="")`
![learnToCodeRPG_python_quiz_ui_bug_steps_to_reproduce_1_wrong](https://user-images.githubusercontent.com/15676972/147287086-782b6984-67f3-45f9-8bc5-78c9a6a28bf9.jpg)
![learnToCodeRPG_python_quiz_ui_bug_steps_to_reproduce_2_wrong](https://user-images.githubusercontent.com/15676972/147287092-7c3c3ff5-b191-4a17-8440-0482b137f549.jpg)
![learnToCodeRPG_python_quiz_ui_bug_steps_to_reproduce_3_wrong](https://user-images.githubusercontent.com/15676972/147287097-82fd25c3-943c-4393-bc72-9e6799e219ee.jpg)

Reproducing the bug and choosing the first `print("Hello, World!", end="")`
![learnToCodeRPG_python_quiz_ui_bug_steps_to_reproduce_1_correct](https://user-images.githubusercontent.com/15676972/147287112-7205843d-1f5d-4960-ba2c-027959d06004.jpg)
![learnToCodeRPG_python_quiz_ui_bug_steps_to_reproduce_2_correct](https://user-images.githubusercontent.com/15676972/147287120-2d69e74f-423b-401c-a949-60c68fa233cc.jpg)

**Comment by RuolinZheng08** [comment]
Same issue as #13. Fixed. Thanks!
