### ISSUE TITLE
Bug report: Error opening github repo link

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/LearnToCodeRPG#16]
### What bug did you encounter?

The program encountered an exception with an open format operation after clicking on a button to open the browser. 

### Steps to Reproduce

At the very end of the game (after I got an ending; in this case the dream dev job after exploding the production server), I clicked a button to ask to check out the source code. After that I got prompted to see if I wanted to view the source code in the browser. I clicked on the button and then an exception occurs. 

### Screenshots

![The Crash](https://user-images.githubusercontent.com/9373245/147296024-7eebd7bf-ea89-4ca7-a029-83d7bf5cb9a7.PNG)

**Comment by RuolinZheng08** [comment]
Fixed in https://github.com/freeCodeCamp/LearnToCodeRPG/commit/1a1be22a87ea47bc64a86767cc58bb896d472aaf. Thanks!
