### ISSUE TITLE
Crash: Date out of range

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/LearnToCodeRPG#17]
### What bug did you encounter?

The game encountered an date of out of range exception when the checklist was going to be formally cleared. I hit the button to proceed and got an exception. 

### Steps to Reproduce

At the end of the month before the formal next day, my character finally got accepted for a job. It occurred when a new week was formally added. 

### Screenshots

[Crash report](https://imgur.com/a/Bg3CGPa)

[Invalid date](https://imgur.com/a/Ku4YYEP) 

### Additional Information

I was fast-forwarding and time traveling a lot if that helps.

**Comment by a2937** [comment]
I'm very confused as the value that makes sense to be there should be November 6th.

**Comment by RuolinZheng08** [comment]
Thanks for the bug report! 
Fixed in 46739d9
See #9 

Please feel free to download the updated version from itch. Your saved game should carry over without a problem.

**Comment by a2937** [comment]
Pardon me Miss Zheng but I can't find a version later than version 1.0 on the itch.io page. In addition I had an question/epiphany last night before I went to bed. What would happen if next week was called if the date was set to October 25th. I believe that is the the date my game was set to.

Here's what probably caused my exception:

```25 (the day of the month) + 7 = 32
32 > 31 
{
  32 - 31 ( days in October) - 1 = 0 
} 
```

**Comment by RuolinZheng08** [comment]
Hi Aaron @a2937. I'm still tagging the bug-fix builds as version 1.0 on itch so feel free to download that :)
I feel like the `- 1` in `self.day = self.day - self.days_count[self.month] - 1` is the thing that's causing the issue so I removed it in 9cf71ad

**Comment by a2937** [comment]
That actually fixed it and is actually way more accurate. 👍

Sometimes the simplest solutions are the best. And here is my formal test by the way. 

[Test gist](https://gist.github.com/a2937/f129bb61b40e510615064e4b242268e9)
