### ISSUE TITLE
Spanish translation - I offer to do it

### ISSUE THREAD

**Issue by cincarnato** [freeCodeCamp/LearnToCodeRPG#18]
### What feature would you like to suggest?

I am playing the game. I think it's an excelent idea.

I propose a spanish translation. I offer to do it.  

The code is prepared for multilanguage? If not... maybe I can create a branch.

**Comment by ieahleen** [comment]
Thank you for your offer, the LearnToCodeRPG will be translated using the same translation pipeline that freeCodeCamp uses for its other products, the Crowdin platform. Join the freeCodeCamp chat at chat.freeCodeCamp.org to meet the Spanish translation team.

**Comment by raisedadead** [comment]
Closing in favor of #41
