### ISSUE TITLE
Missing answer for one of the Python questions

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/LearnToCodeRPG#24]
### What bug did you encounter?

Here is the quiz question:
What is the new line character in Python?
The 4 possibilities should be 
\n
\new
\s
\m
But if you look at the screenshot the correct answer is not displaying. 

### Steps to Reproduce

You can find this question in the python category when doing the study quiz questions.

### Screenshots

<img width="1101" alt="Screen Shot 2021-12-25 at 11 59 54 PM" src="https://user-images.githubusercontent.com/67210629/147402415-ed2779b8-3d27-4dc9-8779-60ecdd9b483d.png">

**Comment by RuolinZheng08** [comment]
Fixed by escaping \
