### ISSUE TITLE
Typo in phrase when all questions are answered correctly

### ISSUE THREAD

**Issue by KostaSav** [freeCodeCamp/LearnToCodeRPG#28]
### What bug did you encounter?

Got the message "I got all questions my right!".
I guess "my" should come before "questions".

### Steps to Reproduce

Get all four questions answered correctly. 
It does not happen every time, in my case, it was in a mix-and-match and not a specific category of questions.

### Screenshots

![syntax_my_questions](https://user-images.githubusercontent.com/38582170/147419414-fa2b93f4-4781-4d2a-91f3-141c64d81137.jpg)

**Comment by RuolinZheng08** [comment]
Fixed in 631ecea20ffe45a42b281c734fc129f0b59ba7b0
