### ISSUE TITLE
Typo in question about background-clip

### ISSUE THREAD

**Issue by KostaSav** [freeCodeCamp/LearnToCodeRPG#33]
### What bug did you encounter?

Got the question "What is the name of the property that clips the background image **to** inside the container?"

I guess `to` is not needed.

### Steps to Reproduce

Get an interview question related to CSS.

### Screenshots

![typo_clip](https://user-images.githubusercontent.com/38582170/147699134-b1c0baa2-0514-444e-aeac-e6f3cc1865b3.jpg)

**Comment by RuolinZheng08** [comment]
@AbbeyRenn Hey Abbey, I think this line reads fine to me. Your thoughts?

**Comment by RuolinZheng08** [comment]
I think the phrase here is **clip [object] to**, so I'm closing this as a non-issue.
