### ISSUE TITLE
Starting a game with a different name overwrite other name in saves

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/LearnToCodeRPG#36]
### What bug did you encounter?

I just started a new game to try to see it wasn't just my impression. I choose the name Robert, then loaded a different save where the name should have been Lydia, and the name was Robert...

### Steps to Reproduce

Have at least a save.
Start a new game. When prompted choose a name different from previous saves.
Now, load a save that should use a different player name. Notice that the name in that save has changed.

**Comment by RuolinZheng08** [comment]
Fixed in c12d614. Will merge into main as we proceed with localization
