### ISSUE TITLE
Synchronize the arrows with the music beats when they hit the bottom line in the rhythm mini-game

### ISSUE THREAD

**Issue by CarlosIvanchuk** [freeCodeCamp/LearnToCodeRPG#37]
### What feature would you like to suggest?

When playing the rhythm mini-game, the action of pressing the arrow bottoms on the keyboard (corresponding to the arrow buttons that appears on the screen) at the time they reach the bottom line feels disconnected from the music that is playing. The moment in which the arrows are supposed to be pressed is not synchronized with the music beats. This makes me concentrate on the visual hints rather than also use the music as a support to make it more enjoyable. I haven't played too much these type of music games before, so I don't know if this is the normal game mechanic.

**Comment by RuolinZheng08** [comment]
This is non-trivial both for the engineer and the musician since we need to separate the beats from the base rhythm (I'm not well-versed in music terminology). Therefore we won't be able to take on this feature 😞
