### ISSUE TITLE
Semicolon does not show in HTML Quiz Question about character entities

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/LearnToCodeRPG#38]
### What bug did you encounter?

Here is the quiz question:
What is the HTML character entity for the ampersand sign?

As you can see in the screenshot, the semicolon is not showing for 3 out of the 4 answers.

The correct answer should be displaying this:
`&amp;`

### Steps to Reproduce

Take a quiz in the HTML section and look for this question.

Here is the quiz question:
What is the HTML character entity for the ampersand sign?

### Screenshots

![Screen Shot 2022-01-01 at 10 32 16 AM](https://user-images.githubusercontent.com/67210629/147857684-22a2bfc9-39b5-404a-81c2-aa3d3df146d0.png)

### Additional Information

I am using a Mac mini to play the game.

**Comment by RuolinZheng08** [comment]
Fixed in 85a6f0b. Thanks!
