### ISSUE TITLE
Update text from "worth learning in 2021" to "2022'. 

### ISSUE THREAD

**Issue by kagusev** [freeCodeCamp/LearnToCodeRPG#39]
### What bug did you encounter?

The slide marked as August 1st  incudes a phrase " tech skills worth to learn in 2021". It makes sense to change it to 2022.

### Steps to Reproduce

Follow the game script until the slide comes up.

### Screenshots

![gameErrors_01](https://user-images.githubusercontent.com/27296397/147893373-fdf5125f-3e75-4a68-9f2c-6d21e04880ed.png)

**Comment by jdwilkin4** [comment]
I think it makes sense to change it to 2022.
The only drawback would be that this would need to be updated every year to stay current.

**Comment by kagusev** [comment]
I opened a pull request for this change. Unless you want to rephrase the text to eliminate the date completely.

**Comment by jdwilkin4** [comment]
I think it would be nice to leave off the year.

**Comment by RuolinZheng08** [comment]
Maybe this will do: bfc3177
"Oh here's a video about the top 10 tech skills worth learning **this year**."
