### ISSUE TITLE
Two identical questions will appear in a row sometimes.

### ISSUE THREAD

**Issue by poemDead** [freeCodeCamp/LearnToCodeRPG#40]
### What feature would you like to suggest?

Avoiding two identical questions in a row can have a better learning result while doing quiz.

### Additional Information

<img width="710" alt="image" src="https://user-images.githubusercontent.com/69440589/147905029-9cd9de36-dde1-472c-b364-94ed9ebb9202.png">

**Comment by jdwilkin4** [comment]
Hi @poemDead ! 

Thank you for bringing up this issue.
This same issue was brought up last week and there is a PR in the works to resolve it. 
https://github.com/freeCodeCamp/LearnToCodeRPG/issues/12

I am going to close this issue since this is a duplicate. 
Thanks!
