### ISSUE TITLE
clarification> August 5: Value associated with an object...

### ISSUE THREAD

**Issue by jeremyfiel** [freeCodeCamp/LearnToCodeRPG#44]
### What bug did you encounter?

While the link provided is for Python and the definition is available on the page, this is subjective to any prior programming language knowledge.

In JavaScript, Objects have `properties`, not `attributes`  [MDN Working With Objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects) 

### Steps to Reproduce

n/a

### Screenshots

![image](https://user-images.githubusercontent.com/32110157/148164204-1c06073d-4bdc-44cf-b6b5-173f5014518f.png)

**Comment by RuolinZheng08** [comment]
Confirmed that it is under `general_cs_questions` in `quiz_questions_from_csv.rpy`

@jdwilkin4 Hi Jessica, would you mind rephrasing this question? Or we may move it to Python questions.

```
    QuizQuestion(
    question="A value associated with an object that can be referenced by its name using dot notation is know as...",
    true="Attribute",
    false=["Property", "Characteristic", "Method"],
    explanation="An attribute is a value associated with an object that can be referenced by its name using dot notation.",
    learn_more_url="https://docs.python.org/3/glossary.html",
    difficulty=1,
    ),
```

**Comment by jdwilkin4** [comment]
I think it would be good to move it to the Python questions. We can also add "In Python" at the beginning of the question so it is more clear that way.
