### ISSUE TITLE
Error in question, 

### ISSUE THREAD

**Issue by franciscomelov** [freeCodeCamp/LearnToCodeRPG#45]
### What bug did you encounter?

In the python section, the question:
What is the modulo operator in Python?

I think the answer should be "%" instead of "%%"

### Steps to Reproduce

choosing the python option.

### Screenshots

![Sin título](https://user-images.githubusercontent.com/17803231/148626354-9338baea-d8d2-45f7-9761-637d939b76ba.png)

**Comment by RuolinZheng08** [comment]
Fixed in f7fc86e. Thanks!
