### ISSUE TITLE
An ability to see the correct answer after it was pushed into a quiz. 

### ISSUE THREAD

**Issue by kagusev** [freeCodeCamp/LearnToCodeRPG#49]
### What feature would you like to suggest?

 Some times user answer question with some uncertainty and if he/she guessed it right the score goes up but user cannot have another look at the selected answer.  It would be great if user could see posted answers. Like click on category in the table and see question/given answer pairs

**Comment by greensleevesbuddy** [comment]
Yes definitely agreed. The quiz feature is awesome for learning CS fundamentals, to make this tool even more helpful for users especially beginner programmers like me who often guess get it correct, but still want to access the "learn more" link to get more complete understanding of the question topic without having to click 'back' and intentionally answer questions wrong just to be able to read up to get more understanding from the topic link. Cheers!
