### ISSUE TITLE
Exception when trying to play video games

### ISSUE THREAD

**Issue by MMTabaka** [freeCodeCamp/LearnToCodeRPG#51]
### What bug did you encounter?

I have encountered an exception screen when trying to play some video games.

### Steps to Reproduce

1. Take a day off and relax
2. Play some video games
3. Click on a song to play (any)

Music starts to play but there is a screen with message: "An exception has occurred"

To return back to game:
1. Ignore (multiple times)
2. Exit at the bottom of the list of songs

### Screenshots

<img width="1522" alt="Screenshot 2022-01-10 at 9 17 34 pm" src="https://user-images.githubusercontent.com/64903229/148840962-f34a573b-fa66-44ba-a1c3-a901c2383fcb.png">

**Comment by RuolinZheng08** [comment]
This should fix it: 266da11
