### ISSUE TITLE
Stats/knowledge values on pop-up not resolving

### ISSUE THREAD

**Issue by AdrianSkar** [freeCodeCamp/LearnToCodeRPG#52]
### What bug did you encounter?

The stats/knowledge pop-up messages look like they're missing the proper/resolved values.

### Steps to Reproduce

1. Download and run the game on linux.
2. Paste saved games files from a Windows device. 
3. Run and continue the game again.

### Screenshots

![image](https://user-images.githubusercontent.com/12052430/149018727-482b3df9-763d-47ed-b784-94e335e305ee.png)

### Additional Information

Saved games (last one being the one where the issue is visible): [saves.zip](https://github.com/freeCodeCamp/LearnToCodeRPG/files/7849779/saves.zip)

**Comment by TeaandOwls** [comment]
Yes - I have this same issue on Windows 10, both when running the game .exe, and when running the code in RenPy.

**Comment by RuolinZheng08** [comment]
Fixed in https://github.com/freeCodeCamp/LearnToCodeRPG/commit/6cd34d7a169b6135687cef971d15e861b78b6e47

Also updated the build on itch. Feel free to verify :)

**Comment by AdrianSkar** [comment]
> Fixed in [6cd34d7](https://github.com/freeCodeCamp/LearnToCodeRPG/commit/6cd34d7a169b6135687cef971d15e861b78b6e47)
> 
> Also updated the build on itch. Feel free to verify :)

Like a charm. Thank you!!
