### ISSUE TITLE
Bug report:  pipe symbol Question glitch

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/LearnToCodeRPG#53]
### What bug did you encounter?

In one of the questions ; there is only 3 answers yet 4 boxes to choose from. Would it be better if the possible question answers on line 3280 of ["quiz_questions_from_csv.rpy](https://github.com/freeCodeCamp/LearnToCodeRPG/blob/main/game/scripts/quiz_questions_from_csv.rpy) be edited to have another possible answer or have the screen adapt to variable length answer possibilities .

### Steps to Reproduce

My character was studying the Linux subjects when this question randomly came up. 

### Screenshots

[Picture of the question](https://i.imgur.com/g5Y735X.png)

### Additional Information

There is a possibility more questions are like this. I haven't browsed the entire quiz questions RenPy file.

**Comment by RuolinZheng08** [comment]
Thanks! Fixed in 945f229
