### ISSUE TITLE
Linux Quiz - Incorrect answer for uname question

### ISSUE THREAD

**Issue by JoeyBrinkman** [freeCodeCamp/LearnToCodeRPG#54]
### What bug did you encounter?

I think one of the Linux quiz questions has an incorrect answer

LearnToCodeRPG-1.0-linux/game/scripts/quiz_questions_from_csv.rpy

QuizQuestion(
    question=_("Which command is used to display the NAME of the operating system?"),
    true=_("uname -s"),
    false=[_("uname -r"), _("uname -k"), _("uname -u")],
    explanation=_("The s option of the uname command prints the Operating System name"),
    learn_more_url="https://www.freecodecamp.org/news/the-linux-commands-handbook/#the-linux-uname-command",
    difficulty=3,
    ),

According to linux manual the tag -s prints the kernel name. I think the correct answer would be -o which print the operating system name.

### Steps to Reproduce

I encountered this incorrect answer when doing the Linux quiz while studying CS fundamentals.

### Screenshots

![man-defenition-uname](https://user-images.githubusercontent.com/45408540/149251866-a4654cd0-923a-41f1-bffc-ec5e4cd17483.png)
![bug](https://user-images.githubusercontent.com/45408540/149251873-c5160e42-60a1-46ea-9055-d6ba774cf037.png)

### Additional Information

Thank you for making this great game! I really appreciate it!

**Comment by a2937** [comment]
It doesn't seem wrong to me. I ran the command on my Windows Subsystem for Linux machine. ![Capture](https://i.imgur.com/XBooD1P.png)

**Comment by JoeyBrinkman** [comment]
Hi Aaron,

Thank you for replying.

I would take a look at this article when you have time.

https://www.gnu.org/gnu/linux-and-gnu.html

Linux is the kernel, which is an essential part of the OS but not the
entire OS. There are many different distros that use Linux kernel plus
additional software from the GNU project to make a fully functional OS. The
Linux kernel alone is not the entire OS.

According to the official Linux manual the tag (-s OR --kernel-name) prints
the kernel name, whereas that tag (-o OR --operating-system) prints the
operating system name.

It's written right in the manual.

uname -o will likely print GNU/Linux which is the full name of the OS. GNU
can be run with a completely different kernel such as FreeBSD to make a
GNU/FreeBSD OS etc.

**Comment by a2937** [comment]
Thank you for this new information. :) I still have quite a few bit to learn apparently. And the companion app might need to be updated too. 

https://github.com/freeCodeCamp/Developer_Quiz_Site

**Comment by RuolinZheng08** [comment]
Thanks @JoeyBrinkman 
Fixed in e7c1a78
@jdwilkin4 
Hi Jessica, would you mind updating developerquiz.org? Thanks!
