### ISSUE TITLE
Skipping doesn't work

### ISSUE THREAD

**Issue by digituar** [freeCodeCamp/LearnToCodeRPG#55]
### What bug did you encounter?

In the view where the selection of
- Take a walk in the park
- Play some video games
- Listen to music
comes, skipping doesn't work

### Steps to Reproduce

continued the normal procedure with next and where the selection came I wanted to skip.

### Screenshots

![skipping](https://user-images.githubusercontent.com/34481389/149369271-2783ba93-e7fa-4aa7-8449-81394989280d.jpg)

**Comment by a2937** [comment]
You'll in the middle of a decision. Skipping doesn't occur unto a decision is made in Renpy or some other condition occurs. I don't think this is an actual bug.

**Comment by a2937** [comment]
Can you clarify something for me? Are you trying to skip this decision screen? In Renpy you can't skip a decision branch normally. The game won't let you. Until you click one of the three options; it'll be stuck on this screen.

**Comment by digituar** [comment]
The point here was not to find a bug, but to improve a functionality. If skipping is not an option in this view, it should probably be disabled. Then it's a suggestion for improvement, sorry
