### ISSUE TITLE
Uncaught Exception Line 1085

### ISSUE THREAD

**Issue by Lauro235** [freeCodeCamp/LearnToCodeRPG#60]
### What bug did you encounter?

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1085, in script call
    call day_activity_choices from _call_day_activity_choices_5
  File "game/scripts/labels/day_activity_choices.rpy", line 36, in script call
    call study_session from _call_study_session_1
  File "game/scripts/labels/quiz_session.rpy", line 41, in script
    $ renpy.say(None, quiz_question.question, interact=False)
  File "game/scripts/labels/quiz_session.rpy", line 41, in <module>
    $ renpy.say(None, quiz_question.question, interact=False)
TypeError: %o format: a number is required, not TagQuotingDict

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1085, in script call
    call day_activity_choices from _call_day_activity_choices_5
  File "game/scripts/labels/day_activity_choices.rpy", line 36, in script call
    call study_session from _call_study_session_1
  File "game/scripts/labels/quiz_session.rpy", line 41, in script
    $ renpy.say(None, quiz_question.question, interact=False)
  File "C:\Users\Lozzy\Saved Games\LearnToCodeRPG-1.0-pc/renpy/ast.py", line 923, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Lozzy\Saved Games\LearnToCodeRPG-1.0-pc/renpy/python.py", line 2235, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/labels/quiz_session.rpy", line 41, in <module>
    $ renpy.say(None, quiz_question.question, interact=False)
  File "C:\Users\Lozzy\Saved Games\LearnToCodeRPG-1.0-pc/renpy/exports.py", line 1406, in say
    what = what % tag_quoting_dict
TypeError: %o format: a number is required, not TagQuotingDict

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
Learn to Code RPG 1.0
Tue Jan 18 12:47:39 2022

### Steps to Reproduce

I had just finished a day off - choice games. The day after I chose CS fundamentals - CSS. I answered the first question correctly and on the second question the uncaught error occurred. Not really sure how to be sure if this would reproduce the problem, but it's as much as I can remember.

Please tell me if there are any techniques I can use to provide you more information for future reports.

### Screenshots

![image](https://user-images.githubusercontent.com/91217473/149941393-68fffc29-0d50-4350-b0bd-acb526b6473e.png)

![image](https://user-images.githubusercontent.com/91217473/149941360-6e61b8d1-91e5-498c-ad7e-70d0b78113e8.png)

### Additional Information

Hi there,

I'd love to be more helpful with how I report issues. If you can give me some tips. I don't know what information is relevant in terms of reproducing the problem... Do you want me to give extra game play information? Obviously, I don't want to waste your time if the information isn't relevant. I've had a couple of uncaught errors since re-downloading. When I rolled back after the first uncaught error. It seemed changing my path prevented the same error, but here I am a bit later encountering a new error (or possibly the same one as before)

Thanks for the hard work!

**Comment by googlebleh** [comment]
your screenshots contained more than enough info to diagnose the problem

I'm 95% sure this exception is caused by one of these two questions
```
cwee@cwee-HP-ZBook-Studio-G7 22:36:53 ~/repos/LearnToCodeRPG fix/renpy_say_format
$ grep -rn "question.*%"
game/scripts/quiz_questions_from_csv.rpy:781:    question=_("Which one of these values represents 10% of the viewport width?"),
game/scripts/quiz_questions_from_csv.rpy:797:    question=_("Which one of these values represents 20% of the viewport height?"),
```
hopefully that sounds familiar to you

I've added more technical details in the PR comments

**Comment by Lauro235** [comment]
Thanks for the reply and I'm happy that the screen shots were helpful!
