### ISSUE TITLE
Stat increases / decreases not showing properly

### ISSUE THREAD

**Issue by DuxVictorum** [freeCodeCamp/LearnToCodeRPG#61]
### What bug did you encounter?

Every time I answer a CS question correctly, my stat increases don't show properly. Instead the message states: 
"[stats_name!t] knowledge increased by [val_str]"
When my sanity decreases after studying, it's the same thing.

### Steps to Reproduce

Every time I study and answer quiz questions, it happens. Happens every time stats go up or down. Consistent from beginning to now.

### Screenshots

![screenshot0002](https://user-images.githubusercontent.com/72815732/150187746-566bb2c0-d43a-49e2-9c12-f57424dbc2d1.png)

### Additional Information

I installed the game on my desktop. That wouldn't have any effect, right?

**Comment by RuolinZheng08** [comment]
Hi @DuxVictorum. 6cd34d7a169b6135687cef971d15e861b78b6e47 should fixed it and the build on itch has been updated.
