### ISSUE TITLE
so how can I help with translating?

### ISSUE THREAD

**Issue by xdlrt** [freeCodeCamp/LearnToCodeRPG#64]
### What feature would you like to suggest?

I want to help with translating chinese simplified version, maybe I can just start with https://freecodecamp.crowdin.com/u/projects/27/l/zh-CN  or create prs for this repo?
This is my first time participating in a freecodecamp translation project.
Thanks for reply.

**Comment by RuolinZheng08** [comment]
@miyaliu666 Hi Miya, would you mind posting relevant links and/or inviting @xdlrt to relevant group chats? Thanks!

**Comment by miyaliu666** [comment]
Hi @xdlrt We're translating on Crowdin. Here's the [guide](https://chinese.freecodecamp.org/forum/t/topic/4593) for translators. And you can choose to join the WeChat group or freeCodeCamp Chat. Thanks!

**Comment by xdlrt** [comment]
thanks, I started translating day_activity_choices and finished about 30%, that's cool.

I will join the WeChat group, great jobs for you.
