### ISSUE TITLE
typo in achievement title

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/LearnToCodeRPG#65]
### What bug did you encounter?

I found a typo in one of the achievement titles.

### Steps to Reproduce

https://github.com/freeCodeCamp/LearnToCodeRPG/blob/94c833a49ec6fe44c6be70c9990a0c23f65d6bfc/game/scripts/variables.rpy#L209

there shoudl be written `Machines`

**Comment by RuolinZheng08** [comment]
Fixed.
