### ISSUE TITLE
wrong tweet for achievement

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/LearnToCodeRPG#67]
### What bug did you encounter?

![image](https://user-images.githubusercontent.com/26656284/153028356-6d99d532-0581-4f30-9a89-95928154913b.png)
with this achievement if I tweet there is the wrong message

![image](https://user-images.githubusercontent.com/26656284/153028414-c653205b-d4fc-4f25-aafc-fb57ae12313d.png)

### Steps to Reproduce

https://github.com/freeCodeCamp/LearnToCodeRPG/blob/dfe67a20f3536f52ccc0336c9e7c39091d6c2c22/game/scripts/variables.rpy#L347

the tweet is the wrong one for the achievement here

**Comment by RuolinZheng08** [comment]
Fixed in [c545fb5](https://github.com/freeCodeCamp/LearnToCodeRPG/commit/c545fb56fcc0eec51a76ce1bdfaf75c4e8ca47c7).
