### ISSUE TITLE
No scroll 

### ISSUE THREAD

**Issue by KaosSpectre** [freeCodeCamp/LearnToCodeRPG#76]
### What bug did you encounter?

On mobile: when we see a document, such as the CupcakeCPU email, that doesn't fit the screen of the device there is no way to scroll. I saw it before on quiz question I believe. But now it's not letting me progress.

### Steps to Reproduce

Received CupcakeCPU email

### Screenshots

![Screenshot_20220728-121328_Learn to Code RPG](https://user-images.githubusercontent.com/97178572/181587080-30f7c4ef-d1b9-47a8-bd86-a145f47b34ee.jpg)

**Comment by RuolinZheng08** [comment]
Fixed in d683c6682a5c654b43057a5db64893db411d5312
