### ISSUE TITLE
How to build LearnToCodeRPG

### ISSUE THREAD

**Issue by rffontenelle** [freeCodeCamp/LearnToCodeRPG#78]
### What bug did you encounter?

I would like to test the Brazilian Portuguese translation of Learn To Code RPG, and first I'd have to pull the translation and then build it. However I don't see build instructions and I'm not sure how to proceed with building Ren'Py projects. Can I have instructions or link to information which I can use to set up the environment and build it?

### Steps to Reproduce

N/A

**Comment by RuolinZheng08** [comment]
Just download Ren'Py https://www.renpy.org/ and when the Ren'Py launcher opens, if it asks you to select a directory, you can select Desktop assuming you cloned the repo to your Desktop. Then simply hit Launch Project and you should be good to go.
![image](https://user-images.githubusercontent.com/35674052/208734737-7292c227-7fc0-451c-bbfc-c130f54cf02d.png)
