### ISSUE TITLE
Windows Exception error

### ISSUE THREAD

**Issue by Jace842016** [freeCodeCamp/LearnToCodeRPG#88]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
When trying to SAVE and you click an empty save slot the following error exception occurs.
**To Reproduce**
1. Start game
2. When first presented with how to save your progress click save button in bottom right corner.
3. Then Save screen appears with empty save slots, click an empty slot. 

**Expected behavior**
Gameplay should  be Saved up to this point in time, but gives an error. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: EDGE
 - Version: 108.0.1462.54 (Official build) (64-bit)

**Additional context**

I was using the APP via the downloaded  ZIP file on windows 11, not via a web browser or smartphone.

![Screenshot 2022-12-24 120414RPG](https://user-images.githubusercontent.com/81299700/209435339-2ce60bb4-41e1-4601-8e58-615d8ca7971a.jpg)
![Screenshot 2022-12-24 120444RPG](https://user-images.githubusercontent.com/81299700/209435356-516d3f74-770e-4ddc-91cd-24a5586d33d2.jpg)

**Comment by Voidcutter** [comment]
Same

**Comment by RuolinZheng08** [comment]
https://github.com/freeCodeCamp/LearnToCodeRPG/commit/c220e63c220cb5ca6b3169b1f771c8524d7d99c1
